declare module 'oref0/lib/determine-basal/determine-basal.js'
declare module 'oref0/lib/basal-set-temp.js'
declare module 'oref0/lib/iob/index.js'
declare module 'oref0/lib/meal/total.js'
declare module 'oref0/lib/glucose-get-last.js'
