# .github/workflows/run_mocha_tests.yml
name: Test

on: [push, workflow_dispatch]

jobs:
  build:
    name: Test

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - run: npm install
      - run: npm run build --if-present
      - run: npm test
